### PR TITLE
Commons IO instead of custom solution

### PR DESCRIPTION
**Pull request by MaciejZiarko**
FilenameUtils.normalizePath() instead of custom solution.

### CODE REVIEW

**Comment by mariuszs** [comment]
What do you think about `String normalized = new URI(path).normalize().getPath();` ?

**Comment by cameleeck** [comment]
You have plexus-utils there so you are probably use [normalize()](http://plexus.codehaus.org/plexus-utils/apidocs/org/codehaus/plexus/util/FileUtils.html#normalize%28java.lang.String%29)

**Comment by szpak** [comment]
@MaciejZiarko Does this method deal also with backslashes on Windows? From JavaDoc it only normalizes path, e.g. removes `/../../`.

**Comment by MaciejZiarko** [comment]
@szpak Yep, there is also the second argument of type boolean that is used to instruct library to also change to Unix style.  Take a look here: https://commons.apache.org/proper/commons-io/javadocs/api-2.4/index.html?org/apache/commons/io/FilenameUtils.html  It was added in Commons IO 2. (Also I built the project on Windows and all tests pass.)
I think that solution by @mariuszs is optimal. No explicit regex + no additional dependencies.

**Comment by MaciejZiarko** [comment]
@szpak URI(path).normalize().getPath() fails 3 tests on Windows. But there is also String separatorsToUnix(String path) and I will use it.

**Comment by szpak** [comment]
Looks gook to me.

Thanks Maciej.

**Pull request merged**
