### PR TITLE
Support for Wiremock scenarios when generating stubs

### PR DESCRIPTION
**Pull request by pawelus**
Related to #182

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Could you please add a test that would show a Groovy DSL with such an entry and how would the wiremock stub look like? 

From that we can try to talk through how the generated test part could look like.

**Comment by pawelus** [comment]
Basic test added.

Problem is that a scenario usually consists of more than 1 stub and it's not possible to put all requests/responses into 1 stub. All stubs will have the same scenario name.

So to generate server tests for scenarios correctly we'd have to group all responses/requests with the same scenarioName and put them as steps into the test.

**Comment by jkubrynski** [comment]
That's OK, but we still have to order steps correctly, which means we probably need some additional property called `order` or something like this

**Comment by pawelus** [comment]
Actually scenarios have requiredScenarioState property that may suffice here (with "Started" being the default Wiremock value for initial scenario state).

Theoretically you may have more than one scenario expecting the same requiredScenarioState but we probably can live with a limit of 1 mock per requiredScenarioState in Accurest.

So you could order steps based on requiredScenarioState and newScenarioState combination.

**Comment by jkubrynski** [comment]
I'm thinking if we want to fully stick to wiremock's scenarios. If we assume whole scenario is placed in the single directory then directory name (which is also used for naming test class) should be equal to scenario name. Then next scenario stages names can be also generated based on some order property. WDYT?

**Comment by pawelus** [comment]
Makes sense. It would simplify creating scenarios and reduce the possibility of ordering/state dependency errors. We just have to remember that for first mock in scenario the requiredScenarioState has to be "Started".

Also if we generate output mocks in the same directory structure then we'd get a clean and nice separation of scenarios from other mocks.

**Comment by pawelus** [comment]
Question is how to sort those mocks properly to support stepwise?

As far as I can see tests are generated on first come first serve basis based on the file names in given directory.

What we would need here is to check the contents of a file for order the value of order property and then sort files accordingly.

So with current stub generation we'd either have to open the file twice which is not time effective or keep contents of all files from a directory in memory once opened which is a memory overkill.

**Pull request closed without merging**
