### PR TITLE
Fix Gradle caching after file modifications

### PR DESCRIPTION
**Pull request by dstepanov**
Not 100% it's going to help

### CODE REVIEW

**Comment by szpak** [comment]
Hmm, it should not be needed. Please build it locally and test before in some project (or an integration test).

**Comment by dstepanov** [comment]
I'm pretty sure the code is not correct, directory needs to be added on plugin initialization not on the action. 

When cached task is not executed it means directory is not added and tests aren't run.

**Comment by dstepanov** [comment]
@szpak I have added test case that proves I'm right, you can checkout, revert plugin changes and run the tests

**Comment by dstepanov** [comment]
@szpak Did you have time to check it?

**Pull request closed without merging**
