### PR TITLE
fix for issue #47 - add async options on request when new async flag set

### PR DESCRIPTION
**Pull request by mattreyuk**
The tests I wrote appear to show this working but I'm running into issues when I add the maven plugin...

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
The branch has conflicts :/ can you rebase against master please?

**Comment by mattreyuk** [comment]
I think I found what was causing my maven plugin issue, I need to make another change to this PR now

**Comment by mattreyuk** [comment]
ok - everything works locally for me now.

**Comment by marcingrzejszczak** [comment]
Looks good :)

**Comment by marcingrzejszczak** [comment]
Congrats on your first contribution :)

**Comment by mattreyuk** [comment]
thanks for all the help :)

**Pull request merged**
